security:
    encoders: # pour encoder les mots de passe
        App\Entity\User:
            algorithm: auto

    providers: # où se trouve les utilisateurs
        in_memory: { memory: ~ }
        in_database:
            entity:
                class: App\Entity\User
                property: mail
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail
    firewalls: # gérer les firewalls pour la protection
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            user_checker:
            provider: in_database

            form_login:
               login_path: app_login
               check_path: app_login
               csrf_token_generator: security.csrf.token_manager
            logout:
               path: app_logout
               target: home
            switch_user: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


    access_control:

        - { path: ^/user/admin, roles: ROLE_ADMIN }
        - { path: ^/user/account, roles: ROLE_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }