security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: firstname
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:    ^/
            http_basic: ~
            user_checker: App\Security\UserChecker
            provider: our_db_provider

            form_login:
               login_path: /security
               check_path: /security
               csrf_token_generator: security.csrf.token_manager
            logout:
               path: /logout
               target: /
            switch_user: ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


    access_control:

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/account, roles: ROLE_USER }