#index:
#    path: /
#    controller: App\Controller\DefaultController::index

userInscription:
  resource: 'routes/user/userInscription.yml'
  prefix: 'inscription'

securityLogin:
  resource: 'routes/security/login.yml'
  prefix: 'login'