#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#resource: 'routes/user/userInscription.yaml'
  #prefix: 'inscription'

#securityLogin:
  #resource: 'routes/security/login.yaml'
  #prefix: 'login'

#userAccount:
  #resource: 'routes/user/userAccount.yaml'
  #prefix: 'userAccount'

#userLogout:
  #resource: 'routes/user/userLogout.yaml'
  #prefix: 'logout'